name: Upload pdf files

on:
  push:
    paths:
      - 'aboutme/*.md'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: aboutme/

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install md-to-pdf # https://github.com/simonhaenisch/md-to-pdf
        run: npm i -g md-to-pdf
      - name: Install Japanese Font
        run: |
          sudo apt install -y fonts-ipafont
          fc-cache -fv
          fc-list | grep -i ipa
      - name: Generate pdf files
        run: md-to-pdf ./*.md
      - name: Upload pdf files
        uses: actions/upload-artifact@v3
        with:
          name: aboutme
          path: aboutme/
